- src/contributing.md
- src/hacking/building-for-android.md
- Update android package name (See servo/servo#32554)
- Reformat a table to make it more readable in a raw text-editor and satisfy a markdown linter.
> Minor documentation fixes

- src/contributing.md
There are some invalid links that used to work properly when they were placed inside https://github.com/servo/servo.
This MR is to fix those invalid URLs.
> fix: Replace invalid urls in contributing.md

- src/hacking/testing.md
There are some incorrect links in testing page.
1. "`update-wpt` on it" navigates users to a page in servo repo, but the page is showing the link to this testing page. This link should point to the header "#updating-web-test-expectations"
2.  Header named `#running-the-tests-manually` doesn't exist. I guess this should be `#running-web-tests-manually`
This PR is to fix those links.
> fix: Replace some links in the testing page

- src/architecture/concurrency-and-parallelism.md
The page regarding WebXR has been migrated from servo repot to this book. This PR is to replace the link.
> fix: Replace link to webxr page with the one in book

- src/hacking/building-for-android.md
Servo (and mozjs) currently [require r26c](https://github.com/servo/servo/blob/9fdaf9bf0c6958356b8e3b4f5d03f838c13c6307/python/servo/platform/build_target.py#L139). 
The version number was taken from the android ndk
github releases: https://github.com/android/ndk/releases/tag/r26c
> android: Update required NDK version

- src/hacking/building-for-android.md
The default architecture specified by `--android` was changed in servo/servo#33379, so this PR updates the documentation to reflect that. In addition this updates the build command for targeting emulators to use the 64-bit version as well.
> android: update the default architecture

- .github/workflows/deploy.yml
- README.md
The last two deploys seem to have failed since mdbook-mermaid has released a new version, I believe this should fix it
> Update mdbook-mermaid tag in deploy.yml

- src/hacking/building-servo.md
- src/hacking/profiling.md
These patches update the [Profiling](https://book.servo.org/hacking/profiling.html) and [Building Servo](https://book.servo.org/hacking/building-servo.html) chapters with new advice around building Servo for benchmarking and profiling purposes. In particular:
- we document the new `production-stripped` (servo/servo#32651) and `profiling` (servo/servo#33432) profiles
- we recommend using `profiling` builds for profiling, rather than release builds with debug info and thin local LTO
- we clarify that `production` builds are more optimised than `release` builds, and they still have symbols
We also fix a typo, `--with-frame-pointers` → `--with-frame-pointer`. That said, we should really enable stack frame pointers by default in all builds, because it’s [now considered best …
> Update build advice for benchmarking and profiling

- src/hacking/editor-support.md
Now that we enforce clippy to pass in CI.
> Use mach cargo-clippy in vscode config

- src/hacking/building-for-openharmony.md
Clarify how to build for HarmonyOS, improve the documentation of the environment varibales and mention `direnv` as a convenient tool to automatically set the environment variables.
> Improve (Open-)Harmony OS build instructions

- src/architecture/layout.md
A couple of links on the layout page were still using a link format from Github Wiki which doesn't work in MdBook. This fixes them to use standard markdown links.
> Fix links on layout page

- src/hacking/editor-support.md
This patch updates references to etc/shell.nix, which was removed in servo/servo#34336.
> Remove etc/shell.nix in favour of shell.nix (servo/servo#34336)

- src/hacking/building-servo.md
In [34340](https://github.com/servo/servo/pull/34340) we optimize `production` profile. This changes updates the book accordingly
> Update `production` profile documentation

- src/hacking/setting-up-your-environment.md
- While building Servo on my Debian system, I encountered the following error:
```Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libgstreamer-plugins-good1.0-dev
E: Couldn't find any package by glob 'libgstreamer-plugins-good1.0-dev'
```
- The build completed successfully without the need to install `libgstreamer-plugins-good1.0-dev`. 
As a result, this dependency has been removed from the Debian section of the configuration. However, a note has been added advising users of Ubuntu-based systems to install it if necessary.
> Remove `gstreamer-plugins-good1.0-dev` from the list of Debian dependencies

- src/running-servoshell.md
The Preference API has changed and this reflect the new API.
> Update link and example of usage of Preferences

- src/contributing.md
- src/hacking/testing.md
Legacy layout has been removed, so we can simplify the documentation.
> update try labels and `mach try` syntax

- src/hacking/using-devtools.md
The instructions in https://github.com/servo/servo/blob/main/etc/devtools_parser.py work inconsistently and are missing required preferences. These steps require no other tools and work consistently for me.
> Add instructions for capturing devtools protocol logs.

- src/getting-servo.md
Warning is no longer applicable.
> Remove old warning about windows clone

- src/hacking/building-servo.md
- Removed `-d` from "To build servoshell for your machine". The flag only sets the build profile to debug, which `./mach build` does on its own and notifies the user about the automatic setting. I can imagine a confused user trying to pass `-d` and another profile thinking `-d` specifies a build target due to the wording.
- To complement the above change, the info about the debug build profile now notes that it is the default.
- `./mach build --android` builds for aarch64 by default now instead of armv7.
- Added a small blurb about `./mach build --help` at the end.
> Tweaks to building-servo.md

- src/hacking/testing.md
There are currently two sections on how to update web platform test expectations:
* https://book.servo.org/hacking/testing.html#updating-a-test
* https://book.servo.org/hacking/testing.html#updating-web-platform-test-expectations
This change removes the first one, as it is less detailed and even contains incorrect information about commits being created by `./mach update-wpt`.
> Remove duplicate section about updating test expectations

- src/hacking/building-for-android.md
The platform is deprecated and the link is dead. See https://github.com/servo/book/pull/108#pullrequestreview-3156194686.
> Remove PandaBoard Android instructions

- .github/workflows/deploy.yml
This is the first step towards https://github.com/servo/servo/issues/38952.  This produces a file which will be available at book.servo.org/links.txt. Every line in the file follows this syntax: `file:line_number:link`.
> ci: Generate a list of links

- .github/workflows/link-health.yml
- link-health.sh
Adds a GitHub action which runs a daily job and produces a text file artifact. The file contains a list of each link and the status code it returned, as well as a brief summary at the end.
Some links are ignored: check the ignore list near the top of the run script for comments on why.
Question: should we use the GitHub action artifact feature or store the logs elsewhere?
> ci: Automated book link health check

- src/hacking/building-servo.md
1. Add references for cross compilation to main page
2. Add reference for build profiles
3. Add full profile option names.
> Add references for Cross Compilation Targets.
